export const TRIPS = [
  {
    id: 1,
    location: "blakesley Gardens",
    activites: "crafting",
    price: 4.99,
    time: "12:00pm",
    pindrop: "link",
    spaces: 25,
    date: "wednesday 18th January",
  },
  {
    id: 1,
    location: "oafield Gardens",
    activites: "running",
    price: 4.99,
    time: "12:00pm",
    pindrop: "link",
    spaces: 25,
    date: "wednesday 18th January",
  },
  {
    id: 1,
    location: "library",
    activites: "reading",
    price: 1.99,
    time: "12:00pm",
    pindrop: "link",
    spaces: 25,
    date: "wednesday 18th January",
  },
  {
    id: 1,
    location: "firestation",
    activites: "safety",
    price: 4.99,
    time: "12:00pm",
    pindrop: "link",
    spaces: 25,
    date: "wednesday 18th January",
  },
  {
    id: 1,
    location: "police station",
    activites: "saftey",
    price: 2.99,
    time: "12:00pm",
    pindrop: "link",
    spaces: 25,
    date: "wednesday 18th January",
  },
];
