export const TRIPS = [
  {
    id: 1,
    event: "Steelhouse lane Police Musuem",
    location: "Birmingham City Center",
    activity: "Education",
    price: 4.99,
    time: "10:00am",
    pindrop: "link",
    spaces: 15,
    date: "wednesday 26th January",
    website: "https://museum.west-midlands.police.uk/",
    address: "The Lock-up ,Steelhouse Lane, Birmingham,B4 6BJ",
    tel: "0121 609 1700",
  },
  {
    id: 2,
    event: "oafield Gardens",
    location: "South Yardley Birmingham",
    activites: "running",
    price: "free",
    time: "12:00pm",
    pindrop: "link",
    spaces: 25,
    date: "wednesday 1st Febuary",
  },
  {
    id: 3,
    event: "cooking Studies Birmingham Library",
    location: "Birmingham City Center",
    activites: "reading",
    price: 1.99,
    time: "12:00pm",
    pindrop: "link",
    spaces: 25,
    date: "wednesday 7th Febuary",
  },
  {
    id: 4,
    event: "Health and saftey  Firestation",
    location: "Garrets Green",
    activites: "safety",
    price: "Free",
    time: "12:00pm",
    pindrop: "link",
    spaces: 25,
    date: "wednesday 9th March",
  },
  {
    id: 5,
    event: "strawberry planting summer season Allotments",
    location: "Bordesley green Birmingham",
    activites: "saftey",
    price: 2.99,
    time: "12:00pm",
    pindrop: "link",
    spaces: 25,
    date: "wednesday 16th March",
  },
];
