export const TRIPS = [
  {
    id: 1,
    event: "Steelhouse lane Police Musuem",
    location: "Birmingham City Center",
    activites: "Education",
    price: 4.99,
    time: "10:00am",
    pindrop: "link",
    spaces: 15,
    date: "wednesday 26th January",
  },
  {
    id: 1,
    event: "oafield Gardens",
    location: "South Yardley Birmingham",
    activites: "running",
    price: "free",
    time: "12:00pm",
    pindrop: "link",
    spaces: 25,
    date: "wednesday 18th January",
  },
  {
    id: 1,
    event: "cooking Studies Birmingham Library",
    location: "Birmingham City Center",
    activites: "reading",
    price: 1.99,
    time: "12:00pm",
    pindrop: "link",
    spaces: 25,
    date: "wednesday 18th January",
  },
  {
    id: 1,
    event: "Health and saftey  Firestation",
    location: "Garrets Green",
    activites: "safety",
    price: "Free",
    time: "12:00pm",
    pindrop: "link",
    spaces: 25,
    date: "wednesday 18th January",
  },
  {
    id: 1,
    event: "strawberry planting summer season Allotments",
    location: "Bordesley green Birmingham",
    activites: "saftey",
    price: 2.99,
    time: "12:00pm",
    pindrop: "link",
    spaces: 25,
    date: "wednesday 18th January",
  },
];
